Example: Deploying to Heroku using long polling
grammyjs/examples pull request #1
Opened 2021-07-13 13:01 UTC by CikiMomogi

2021-07-13 16:12 UTC, Tecardo1 commented
No grammar issues found. But you could make .ts default ;)

2021-07-14 14:46 UTC, wojpawlik requested changes
Webhook is preferable for Heroku. It makes fewer requests, and can be scaled up or put to sleep.

2021-07-14 14:46 UTC, wojpawlik commented on heroku-longpolling.ts
> +const bot = new Bot(''); // <-- put your bot token between the ''
Don't commit the token.
```suggestion
if (process.env.BOT_TOKEN == null) throw new TypeError('BOT_TOKEN missing.');
const bot = new Bot(process.env.BOT_TOKEN);
```

2021-07-14 14:46 UTC, wojpawlik commented on heroku-longpolling.ts
> +├── bot.js
Using root directory for build artifacts quickly gets messy.

```suggestion
├── src/bot.ts
├── lib/bot.js
```

`lib/` and `node_modules/` should be gitignored.

2021-07-14 14:46 UTC, wojpawlik commented on heroku-longpolling.ts
> +├── tsconfig.json
Example `tsconfig.json` would be nice. https://www.npmjs.com/package/@tsconfig/node14?

2021-07-14 14:46 UTC, wojpawlik commented on heroku-longpolling.ts
> +3. Final step: Deploy to heroku
https://blog.heroku.com/six-strategies-deploy-to-heroku

2021-07-14 14:46 UTC, wojpawlik commented on heroku-longpolling.ts
> +├── package.json
`package.json` should contain
```jsonc
{
	"scripts": {
		"build": "tsc"
	}
}
```

2021-07-14 16:53 UTC, CikiMomogi commented
> 
> 
> Webhook is preferable for Heroku. It makes fewer requests, and can be scaled up or put to sleep.

Agree. I have a plan to make the webhook version. I also already wrote the warning about the disadvantage [here ](https://github.com/CikiMomogi/examples/blob/f31ed31fd40b0cfd76b39f7d1050d82ebf508455/heroku-longpolling.ts#L26-L28)

2021-07-14 17:09 UTC, CikiMomogi commented on heroku-longpolling.ts
> +const bot = new Bot(''); // <-- put your bot token between the ''
done

2021-07-14 17:20 UTC, KnorpelSenf commented
In order to increase the visibility and accessibility of this tutorial, I would prefer to publish your work prominently on the website rather than in the comments of an example bot. If you want to show code examples (which makes sense), you could either integrate them as code blocks, or reference the corresponding example bot with a hyperlink.

Either way, it makes sense to limit the content on the example bots repository to executable code. Note that there's a way to run example bots (see README file). The file added in this PR does not compile as-is.

If you want to provide a project template as several files, we may want to add a new directory that features a self-contained example bot setup for Heroku. This would either have a README file, or an article on the website, or both.

2021-07-14 17:30 UTC, CikiMomogi commented
Sounds good to me. I will publish them on the [website ](https://github.com/CikiMomogi/website/blob/main/site/docs/hosting/heroku.md ) then. You can close this pull request.

2021-07-15 14:17 UTC, closed without merging