Add Docker examples
grammyjs/examples pull request #24
Opened 2023-02-18 11:06 UTC by deptyped

2023-02-18 11:15 UTC, roj1512 commented on docker-deno/docker-compose.yml
> +            - BOT_TOKEN= # <-- place your token here
Really?

2023-02-18 11:23 UTC, roj1512 commented on docker-deno/docker-compose.yml
> +            - BOT_TOKEN= # <-- place your token here
Still. Why would the bot token be hardcoded in the compose file?

2023-02-18 11:25 UTC, deptyped commented on docker-deno/docker-compose.yml
> +            - BOT_TOKEN= # <-- place your token here
To keep the example as simple as possible. Do you think it would be better to put it in an .env file?

2023-02-18 11:30 UTC, roj1512 commented on docker-deno/docker-compose.yml
> +            - BOT_TOKEN= # <-- place your token here
Yes, it’s even more simpler.

2023-02-18 12:35 UTC, roj1512 commented on docker-deno/.env
> +# Set your bot token (get it from https://t.me/BotFather)
Spoon-feed

2023-02-18 14:44 UTC, KnorpelSenf commented on docker-deno/main.ts
> +export const bot = new Bot(Deno.env.get("BOT_TOKEN"))
Does this compile?

2023-02-18 15:02 UTC, deptyped commented on docker-deno/main.ts
> +export const bot = new Bot(Deno.env.get("BOT_TOKEN"))
Indeed, `deno check` throws a type error. Wasn't aware that `deno run' didn't check types.

2023-02-18 15:11 UTC, KnorpelSenf commented on docker-deno/main.ts
> +export const bot = new Bot(Deno.env.get("BOT_TOKEN"))
It used to, but this was dropped maybe a year ago due to performance reasons.

2023-02-18 17:53 UTC, KnorpelSenf approved these changes
LGTM, thank you so much!

2023-02-18 18:39 UTC, roj1512 requested changes

2023-02-18 18:39 UTC, roj1512 commented on docker-deno/Dockerfile
> +# Cache the dependencies as a layer (the following two steps are re-run only when deps.ts is modified).
```suggestion
# Cache the dependencies as a layer (the following two steps are rerun only when deps.ts is modified).
```

2023-02-18 18:39 UTC, roj1512 commented on docker-deno/Dockerfile
> +# Ideally cache deps.ts will download and compile _all_ external files used in main.ts.
```suggestion
# Ideally, the following command will download and compile _all_ external files used in main.ts.
```

2023-02-18 18:39 UTC, roj1512 commented on docker-deno/Dockerfile
> +# These steps will be re-run upon each file change in your working directory:
```suggestion
# The following steps will be rerun upon each file change in your working directory.
```

2023-02-18 18:39 UTC, roj1512 commented on docker-deno/Dockerfile
> +# Type-check
```suggestion
# Type check
```

2023-02-18 18:39 UTC, roj1512 commented on docker-deno/Dockerfile
> +RUN deno cache main.ts
Move this above `deno check`?

2023-02-18 18:39 UTC, roj1512 commented on docker-deno/README.md
> +This example illustrates how to run a Deno bot using Docker.
```suggestion
This example illustrates how to use Docker to run grammY bots written for Deno.
```

2023-02-18 18:39 UTC, roj1512 commented on docker-node/README.md
> +This example illustrates how to run a Node.js bot using Docker.
```suggestion
This example illustrates how to use Docker to run grammY bots written for Node.js.
```

2023-02-18 18:44 UTC, KnorpelSenf commented on docker-deno/Dockerfile
> +RUN deno cache main.ts
Let's just merge them to `deno cache --check=all main.ts`

2023-03-11 20:14 UTC, habemuscode reviewed
Nice example's addition, was interested in take a look at this topic

2023-03-11 20:16 UTC, roj1512 commented on docker-node/.env
> +BOT_TOKEN= # <-- place your token here
`.env` should not be uploaded to Git.

2023-03-11 20:18 UTC, KnorpelSenf commented on docker-node/.env
> +BOT_TOKEN= # <-- place your token here
Do you want to rename it to `.env.example`?

2023-03-11 20:27 UTC, roj1512 commented on docker-node/.env
> +BOT_TOKEN= # <-- place your token here
This is a question for @deptyped.

2023-06-16 22:45 UTC, KnorpelSenf commented
@roj1512 can we merge this now? @deptyped can we still merge this?

2023-06-17 09:05 UTC, roj1512 commented on README.md
> +## [Dockerizing Node.js Bot Example »](./docker-node)
```suggestion
## [Docker Example (Deno) »](./docker-deno)

Example Deno bot that can run using Docker.

## [Docker Example (Node.js) »](./docker-node)
```

2023-06-17 09:05 UTC, roj1512 commented on docker-deno/README.md
> +## Dockerizing Deno Bot Example
```suggestion
## Docker Example (Deno)
```

2023-06-17 09:06 UTC, roj1512 commented on docker-node/README.md
> +## Dockerizing Node.js Bot Example
```suggestion
## Docker Example (Node.js)
```

2023-06-17 09:07 UTC, roj1512 commented on docker-deno/Dockerfile
> +RUN deno cache --check=all main.ts
I think only the main.ts should be checked since deps.ts is usually no more used in applications.

```dockerfile
RUN deno check main.ts
```

2023-06-20 06:01 UTC, deptyped commented on docker-deno/Dockerfile
> +RUN deno cache --check=all main.ts
@roj1512 how about this?
```suggestion
COPY . .
# Type check and compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache --check main.ts
```

2023-06-20 06:53 UTC, roj1512 commented on docker-deno/Dockerfile
> +RUN deno cache --check=all main.ts
Yes.

2023-06-20 06:57 UTC, roj1512 approved these changes

2023-06-20 06:58 UTC, merged