chore: add suggestion for show image in submenu
grammyjs/examples pull request #7
Opened 2021-12-03 15:09 UTC by habemuscode

**User flow**

- User write /start and a list of dishes appears. It's just an `Inline Keyboard` with one button per dish
- User clicks on any of the buttons (pizza, for example). The previous `Inline Keyboard` is removed and appears a photo with some empty caption and another `Inline Keyboard` to manage paginations, add to favorites, or other actions

2021-12-03 15:55 UTC, KnorpelSenf commented
Can you resolve the merge conflicts before I review?

2021-12-03 16:03 UTC, KnorpelSenf requested changes
I will push a commit to this branch that changes your code to how it should work.

2021-12-03 16:03 UTC, KnorpelSenf commented on menu.ts
> +  createMessageMedia(ctx, pizzaDatabase[0], createDishMenu(ctx.match))
This is a side-effect. Whenever the menu is rendered, a message will be sent. This is not how the menu plugin is intended to be used.

2021-12-03 16:03 UTC, KnorpelSenf commented on menu.ts
> +    const message = ctx.replyWithPhoto(
You are not awaiting the promise, and the variable is unused.

2021-12-03 16:29 UTC, habemuscode commented on menu.ts
> +    const message = ctx.replyWithPhoto(
Yes, I forget to refactor this for the PR. In the original code (working without the menu plugin), I have `ctx.session.messageId = reply.message_id` to store this ID for future editing and also with the await, but I only remove the await. Thanks for the input

2021-12-03 16:42 UTC, KnorpelSenf commented
I split up the changes in three commits. The middle one is the most important one.

- 947126a6a88f9290dcf6ca1b56f3c48607641158 only fixes formatting. It is not interesting.
- ed528dc253d207b9c709d7cf082619b229883405 applies the real changes, here you can see how it should work
- 2930a6cef69db64fc2a8cc1e1371776bdc8c5bbb does a lot of renaming from `dish` to `pizza`, and some minor changes. It creates a large diff, so I did not want to include it right away, but it is not really that interesting.

2021-12-03 16:57 UTC, KnorpelSenf commented
You should maybe run the code and check if the user flow is what you're expecting it to be.

2021-12-06 07:54 UTC, KnorpelSenf requested changes
Please revert all changes to `menu.ts`. It is a good idea to add this example as an independent file. The current menu example should not be touched.

2021-12-06 20:45 UTC, habemuscode commented
@KnorpelSenf I revert the changes but appear in diff because the `.editorconfig` (indent_size = 4) are applied and previously was committed without.

2021-12-06 22:00 UTC, KnorpelSenf approved these changes
Thank you for your work!

2021-12-06 22:00 UTC, merged